#configure server port number
server:
  port: 7100
  
#configuring app name and gateway routes
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
             - Path=/doctor/**
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
             - Path=/patient/**
        
        